steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/unshift:$SHORT_SHA'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/unshift:$SHORT_SHA'
- name: 'gcr.io/$PROJECT_ID/kustomize'
  dir: 'infra'
  args:
  - 'edit'
  - 'set'
  - 'image'
  - 'unshift=gcr.io/$PROJECT_ID/unshift:$SHORT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-west1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=unshift-dev'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '-k'
  - 'infra'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-west1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=unshift-dev'
