apiVersion: v1
kind: Service
metadata:
  labels:
    app: actions-api
  name: api-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32340
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: actions-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.247.50.13
