apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: actions-worker-cron
spec:
  schedule: '*/1 * * * *'
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: worker
            image: unshift
            command: ['python', '-u', 'worker.py']
            envFrom:
            - configMapRef:
                name: actions-config
            - secretRef:
                name: actions-secrets
