apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cron
spec:
  schedule: '*/1 * * * *'
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: worker
            image: unshift
            command: ['python', 'worker.py']
          restartPolicy: OnFailure
