apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: unshift
nameSuffix: -dev
images:
- name: unshift
  newName: gcr.io/dummy-project/unshift
  newTag: latest
resources:
- cronjob.yaml
